---
title: "Hate Incidents Clean-Up"
author: "Olga Chyzh"
date: "November 20, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Libraries:
```{r}
library(tools)
```



Open data collected by each coder:
```{r}
derek<-read.csv("Derek/DT_First1500.csv", header=TRUE) #First 1500
colnames(derek)[1]<-"Incident.number" #create an incident id variable to help select relevant cases to merge

#tate<-read.csv("Tate/Google_github_hatecrimes01.csv", header=TRUE) 
#tate<-read.csv("Tate/Google_github_hatecrimes2.csv", header=TRUE) #First 1419, 2000-5709

tate<-read.csv("Tate/Google_github_hatecrimes4.csv", header=TRUE) #reopen Tate's data to add the Incident.number variable
tate<-subset(tate, subset=(Hate.Incident==1))
colnames(tate)[1]<-"Incident.number" #create an incident id variable to help select relevant cases to merge


sara<-read.csv("Sara/google_github_hatecrimes_sara.csv", header=TRUE) #2001-2300
sara<-subset(sara, subset=!is.na(Hate.Incident))
colnames(sara)[1]<-"Incident.number" #create an incident id variable to help select relevant cases to merge

ike<-read.csv("Ike/data.csv", header=TRUE) #4000-5761
ike<-ike[-(1:5),] #remove demo rows
ike<-subset(ike, subset=(Hate.Incident==1))


```

Combine Derek and Tate (first 700):
```{r}
mydata<-merge(derek, tate, by=c("Incident.number"), all.x=TRUE)

#Clean up city names:
mydata$Incident.City.x<-as.character(mydata$Incident.City.x)
mydata$Incident.City.y<-as.character(mydata$Incident.City.y)

mydata$Incident.City.x<-trimws(mydata$Incident.City.x, which = c("both"))
mydata$Incident.City.y<-trimws(mydata$Incident.City.y, which = c("both"))

mydata$Incident.City.y[mydata$Title=="New Jersey Garden State Equality LGBT Rights Group Office Vandalized In Possible Hate Crime"]<-"Asbury Park"
mydata$Year.of.Incident.x<-as.numeric(as.character(mydata$Year.of.Incident.x))
mydata$Year.of.Incident.y<-as.numeric(as.character(mydata$Year.of.Incident.y))
mydata$Day.of.Incident.x<-as.numeric(as.character(mydata$Day.of.Incident.x))
mydata$Day.of.Incident.y<-as.numeric(as.character(mydata$Day.of.Incident.y))
mydata$Month.of.Incident.x<-as.numeric(as.character(mydata$Month.of.Incident.x))
mydata$Month.of.Incident.y<-as.numeric(as.character(mydata$Month.of.Incident.y))
mydata$Notes.x<-as.character(mydata$Notes.x)
mydata$Notes.y<-as.character(mydata$Notes.y)

mydata$Title<-mydata$Title.x
mydata$URL<-mydata$URL.x

#Clean up some entries:
mydata$Day.of.Incident.x[mydata$Title=="Couple Refuses To Remove Racial Slur Graffiti From Home"]<-mydata$Day.of.Incident.y[mydata$Title=="Couple Refuses To Remove Racial Slur Graffiti From Home"]<-14
mydata$Day.of.Incident.x[mydata$Title=="Police investigate anti-Muslim flier at Louisiana mosque"]<-mydata$Day.of.Incident.y[mydata$Title=="Police investigate anti-Muslim flier at Louisiana mosque"]<-14

mydata$Day.of.Incident.x[mydata$Title=="Synagogue Hate Crime Suspect An Educated, Suburban Accountant"]<-mydata$Day.of.Incident.y[mydata$Title=="Synagogue Hate Crime Suspect An Educated, Suburban Accountant"]<-4

mydata$Day.of.Incident.x[mydata$Title=="Enraged Auburn man tells Mexican neighbor to leave US, prosecutors say"]<-mydata$Day.of.Incident.y[mydata$Title=="Enraged Auburn man tells Mexican neighbor to leave US, prosecutors say"]<-31

mydata$Day.of.Incident.x[mydata$Title=="Four Frisco Men Charged with Federal Hate Crimes for Targeting Gay Men"]<-mydata$Day.of.Incident.y[mydata$Title=="Four Frisco Men Charged with Federal Hate Crimes for Targeting Gay Men"]<-17
mydata$Month.of.Incident.x[mydata$Title=="Four Frisco Men Charged with Federal Hate Crimes for Targeting Gay Men"]<-mydata$Month.of.Incident.y[mydata$Title=="Four Frisco Men Charged with Federal Hate Crimes for Targeting Gay Men"]<-1
mydata$Notes.x[mydata$Incident.number==1379]<-"Anthony Shelton, Nigel Garrett, Chancler Encalade and Cameron Ajiduah"
mydata$Incident.City.x[mydata$Incident.number==1379]<-mydata$Incident.City.y[mydata$Incident.number==1379]<-"Frisco"

mydata$Day.of.Incident.x[mydata$Title=="Junction City gunman to face hate crime charges"]<-mydata$Day.of.Incident.y[mydata$Title=="Junction City gunman to face hate crime charges"]<-6

mydata$Day.of.Incident.x[mydata$Title=="DA: Junction City standoff being investigated as hate crime - WAOW - Newsline 9, Wausau News, Weather, Sports"]<-mydata$Day.of.Incident.y[mydata$Title=="DA: Junction City standoff being investigated as hate crime - WAOW - Newsline 9, Wausau News, Weather, Sports"]<-6

mydata$Day.of.Incident.x[mydata$Title=="FBI Investigating Deadly Bar Shootings of Indians as Possible Hate Crime"]<-mydata$Day.of.Incident.y[mydata$Title=="FBI Investigating Deadly Bar Shootings of Indians as Possible Hate Crime"]<-22
mydata$Month.of.Incident.x[mydata$Title=="FBI Investigating Deadly Bar Shootings of Indians as Possible Hate Crime"]<-mydata$Month.of.Incident.y[mydata$Title=="FBI Investigating Deadly Bar Shootings of Indians as Possible Hate Crime"]<-2

mydata$Month.of.Incident.x[mydata$Title=="Eye on Boise: Vandalism at Anne Frank memorial called hate crime; community support for memorial swells"]<-3
mydata$Day.of.Incident.x[mydata$Title=="Eye on Boise: Vandalism at Anne Frank memorial called hate crime; community support for memorial swells"]<-7
mydata$Year.of.Incident.x[mydata$Title=="Eye on Boise: Vandalism at Anne Frank memorial called hate crime; community support for memorial swells"]<-2017

mydata$Month.of.Incident.x[mydata$Title=="Hate-Filled Note Against Muslims Stokes Fear at Des Moines Mosque"]<-3
mydata$Day.of.Incident.x[mydata$Title=="Hate-Filled Note Against Muslims Stokes Fear at Des Moines Mosque"]<-12

mydata$Day.of.Incident.x[mydata$Title=="Virginia man charged with hate crime after pulls woman from her car"]<-4
mydata$Month.of.Incident.x[mydata$Title=="Virginia man charged with hate crime after pulls woman from her car"]<-5

mydata$Day.of.Incident.x[mydata$Title=="LASD Investigating Hate Crime in Malibu West"]<-mydata$Day.of.Incident.y[mydata$Title=="LASD Investigating Hate Crime in Malibu West"]<-12
mydata$Month.of.Incident.x[mydata$Title=="LASD Investigating Hate Crime in Malibu West"]<-mydata$Month.of.Incident.y[mydata$Title=="LASD Investigating Hate Crime in Malibu West"]<-3

mydata$Day.of.Incident.x[mydata$Title=="Far West Side man indicted for hate crime in desecration of mosque"]<-mydata$Day.of.Incident.y[mydata$Title=="Far West Side man indicted for hate crime in desecration of mosque"]
mydata$Month.of.Incident.x[mydata$Title=="Far West Side man indicted for hate crime in desecration of mosque"]<-mydata$Month.of.Incident.y[mydata$Title=="Far West Side man indicted for hate crime in desecration of mosque"]

mydata$match_city<-as.numeric(mydata$Incident.City.x==mydata$Incident.City.y)
mydata$match_month<-as.numeric(as.character(mydata$Month.of.Incident.x)==as.character(mydata$Month.of.Incident.y))

#Combine the data on which the coders agree:
agree<-subset(mydata, subset=(match_city==1 & match_month==1))
agree<-subset(agree, subset=!is.na(Month.of.Incident.x))

#Remove old incidents:
agree<-subset(agree, subset=Year.of.Incident.x>2016)



#Additional Incidents Found by Re-Reading the Sources:
inc1<-cbind.data.frame(Title="Police investigate anti-Muslim signs placed at Bossier mosque.1",
                       URL="https://www.shreveporttimes.com/story/news/2017/02/16/police-investigate-anti-muslim-signs-placed-bossier-mosque/98001022/",
                       day=29,
                       month=1,
                       year=2017,
                       city="Bossier City",
                       state="Louisiana",
                       type="offensive flier",
                       issue="race",
                       numdeaths=0,
                       numvic="more than 1",
                       numperp="more than 1",
                       intensity= "2",
                       notes=as.character("Additional incident found in article"),
                       inc.id= 17.1)



inc2<-cbind.data.frame(Title="Four Frisco Men Charged with Federal Hate Crimes for Targeting Gay Men.1",
                       URL="http://www.nbcdfw.com/news/local/Four-Frisco-Men-Charged-with-Federal-Hate-Crimes-for-Targeting-Gay-Men-421945343.html",
                       day=17,
                       month=1,
                       year=2017,
                       city="Plano",
                       state="Texas",
                       type="home invasion",
                       issue="LGBT",
                       numdeaths=0,
                       numvic=1,
                       numperp=4,
                       intensity=3,
                       notes=as.character("add inc--Anthony Shelton, Nigel Garrett, Chancler Encalade and Cameron Ajiduah"),
                       inc.id=1379.1)

inc3<-cbind.data.frame(Title="Four Frisco Men Charged with Federal Hate Crimes for Targeting Gay Men.2",
                       URL="http://www.nbcdfw.com/news/local/Four-Frisco-Men-Charged-with-Federal-Hate-Crimes-for-Targeting-Gay-Men-421945343.html",
                       day=7,
                       month=2,
                       year=2017,
                       city="Plano",
                       state="Texas",
                       type="home invasion",
                       issue="LGBT",
                       numdeaths=0,
                       numvic=1,
                       numperp=4,
                       intensity=3,
                       notes=as.character("add inc--Anthony Shelton, Nigel Garrett, Chancler Encalade and Cameron Ajiduah"),
                       inc.id=1379.2)

inc4<-cbind.data.frame(Title="Four Frisco Men Charged with Federal Hate Crimes for Targeting Gay Men.3",
                       URL="http://www.nbcdfw.com/news/local/Four-Frisco-Men-Charged-with-Federal-Hate-Crimes-for-Targeting-Gay-Men-421945343.html",
                       day=7,
                       month=2,
                       year=2017,
                       city="Aubrey",
                       state="Texas",
                       type="home invasion",
                       issue="LGBT",
                       numdeaths=0,
                       numvic=1,
                       numperp=4,
                       intensity=3,
                       notes=as.character("add inc--Anthony Shelton, Nigel Garrett, Chancler Encalade and Cameron Ajiduah"),
                       inc.id=1379.3)


newdata<-cbind.data.frame(Title=agree$Title,URL=agree$URL)
newdata$day<-agree$Day.of.Incident.x
newdata$month<-agree$Month.of.Incident.x
newdata$year<-agree$Year.of.Incident.x
newdata$city<-agree$Incident.City.y
newdata$state<-agree$Incident.State.y
newdata$type<-agree$Incident.Type.y
newdata$issue<-agree$Issue.Identity.y
newdata$numdeaths<-agree$Num.Deaths.y
newdata$numvic<-agree$Num.Victims.y
newdata$numperp<-agree$Num.Perp.y
newdata$intensity<-agree$Inc.Intensity.y
newdata$notes<-as.character(paste(agree$Notes.x,agree$Notes.y))
newdata$inc.id<-agree$Incident.number

agree<-agree[, order(names(agree))]
agree<-agree[order(agree$Month.of.Incident.x),]


#Combine the data on which the coders disagree:
disagree<-subset(mydata, subset=(match_city!=1 | match_month!=1 | is.na(match_month)))

disagree1<-subset(disagree, subset=(Year.of.Incident.x==2017 | Year.of.Incident.y==2017))

#If they agree on the city:
disagree1_city<-subset(disagree1, subset=(match_city==1))

newdata1<-cbind.data.frame(Title=disagree1_city$Title,URL=disagree1_city$URL)
newdata1$day<-disagree1_city$Day.of.Incident.x
newdata1$month<-disagree1_city$Month.of.Incident.x
newdata1$year<-disagree1_city$Year.of.Incident.x
newdata1$type<-disagree1_city$Incident.Type.y
newdata1$issue<-disagree1_city$Issue.Identity.y
newdata1$city<-disagree1_city$Incident.City.y
newdata1$state<-disagree1_city$Incident.State.y
newdata1$numdeaths<-disagree1_city$Num.Deaths.y
newdata1$numvic<-disagree1_city$Num.Victims.y
newdata1$numperp<-disagree1_city$Num.Perp.y
newdata1$intensity<-disagree1_city$Inc.Intensity.y
newdata1$notes<-as.character(paste(disagree1_city$Notes.x,disagree1_city$Notes.y))
newdata1$inc.id<-disagree1_city$Incident.number


#If they agree on month, but disagree on city:
disagree1_mo<-subset(disagree1, subset=(match_city==0 & match_month==1))

#Correct some cities:
newdata2<-cbind.data.frame(Title=disagree1_mo$Title,URL=disagree1_mo$URL)
newdata2$day<-disagree1_mo$Day.of.Incident.x
newdata2$month<-disagree1_mo$Month.of.Incident.x
newdata2$year<-disagree1_mo$Year.of.Incident.x
newdata2$type<-disagree1_mo$Incident.Type.y
newdata2$issue<-disagree1_mo$Issue.Identity.y
newdata2$city<-disagree1_mo$Incident.City.y
newdata2$state<-disagree1_mo$Incident.State.y
newdata2$numdeaths<-disagree1_mo$Num.Deaths.y
newdata2$numvic<-disagree1_mo$Num.Victims.y
newdata2$numperp<-disagree1_mo$Num.Perp.y
newdata2$intensity<-disagree1_mo$Inc.Intensity.y
newdata2$notes<-as.character(paste(disagree1_mo$Notes.x,disagree1_mo$Notes.y))
newdata2$inc.id<-disagree1_mo$Incident.number

#Data on which the coders disagree:
disagree1_any<-subset(disagree1, subset=(match_city==0 & match_month==0))

#Clean up:
disagree1_any$Day.of.Incident.x<-as.numeric(disagree1_any$Day.of.Incident.x)
disagree1_any$Day.of.Incident.y<-as.numeric(disagree1_any$Day.of.Incident.y)
disagree1_any$Month.of.Incident.x<-as.numeric(disagree1_any$Month.of.Incident.x)
disagree1_any$Month.of.Incident.y<-as.numeric(disagree1_any$Month.of.Incident.y)
disagree1_any$Day.of.Incident.x[disagree1_any$Title=="2 charged in videotaped beating get private attorneys"]<-31

disagree1_any$Day.of.Incident.x[disagree1_any$Title=="Far West Side man indicted for hate crime in desecration of mosque"]<-11
disagree1_any$Month.of.Incident.x[disagree1_any$Title=="Far West Side man indicted for hate crime in desecration of mosque"]<-2

disagree1_any$Day.of.Incident.x[disagree1_any$Title=="Jewish cemetery vandalized; Cuomo starts investigation"]<-3
disagree1_any$Month.of.Incident.x[disagree1_any$Title=="Jewish cemetery vandalized; Cuomo starts investigation"]<-2
disagree1_any$Incident.City.y[disagree1_any$Title=="Jewish cemetery vandalized; Cuomo starts investigation"]<-disagree1_any$Incident.City.x[disagree1_any$Title=="Jewish cemetery vandalized; Cuomo starts investigation"]
disagree1_any$Incident.State.y[disagree1_any$Title=="Jewish cemetery vandalized; Cuomo starts investigation"]<-disagree1_any$Incident.State.x[disagree1_any$Title=="Jewish cemetery vandalized; Cuomo starts investigation"]

disagree1_any<-subset(disagree1_any, subset=Title %in% c("Far West Side man indicted for hate crime in desecration of mosque","Jewish cemetery vandalized; Cuomo starts investigation"))
newdata3<-cbind.data.frame(Title=disagree1_any$Title,URL=disagree1_any$URL)
newdata3$day<-disagree1_any$Day.of.Incident.x
newdata3$month<-disagree1_any$Month.of.Incident.x
newdata3$year<-disagree1_any$Year.of.Incident.x
newdata3$type<-disagree1_any$Incident.Type.y
newdata3$issue<-disagree1_any$Issue.Identity.y
newdata3$city<-disagree1_any$Incident.City.y
newdata3$state<-disagree1_any$Incident.State.y
newdata3$numdeaths<-disagree1_any$Num.Deaths.y
newdata3$numvic<-disagree1_any$Num.Victims.y
newdata3$numperp<-disagree1_any$Num.Perp.y
newdata3$intensity<-disagree1_any$Inc.Intensity.y
newdata3$notes<-as.character(paste(disagree1_any$Notes.x,disagree1_any$Notes.y))
newdata3$inc.id<-disagree1_any$Incident.number


newdata_all<-rbind.data.frame(newdata,newdata1,newdata2, newdata3, inc1, inc2, inc3, inc4)

newdata_all<-newdata_all[, order(names(newdata_all))]
newdata_all<-newdata_all[order(newdata_all$city),]

newdata_all<-unique(newdata_all)
newdata_all<-subset(newdata_all, year==2017)

#Manually remove duplicates:
newdata_all$notes<-" "
newdata_all$notes[newdata_all$inc.id==1379]<-"Anthony Shelton, Nigel Garrett, Chancler Encalade and Cameron Ajiduah"
newdata_all$notes[newdata_all$Title=="First-degree murder charge filed in possible hate crime shooting at Olathe's Austins bar"]<-"duplicate"
newdata_all$notes[newdata_all$Title=="Umbrella-wielding bigot clobbers Hispanic woman in Queens after yelling: 'Get the f--k out of my country!'"]<-"umbrella attack"
newdata_all$notes[newdata_all$Title=="NYPD: Subway Rider Punched In The Face & Told To 'Go Back' To Mexico In Possible Hate Crime"]<-"punching on J train"
newdata_all$notes[newdata_all$Title=="Cops Say This Man Broke Subway Rider's Nose, Told Him 'Go Back To Your Country'"]<-"duplicate"
newdata_all$notes[newdata_all$Title=="OCC student charged with hate crime"]<-"carving swastika into vehicle"
newdata_all$notes[newdata_all$Title=="Police investigating apparent anti-semitic hate crime at UC Hastings dorm"]<-"mezuzah burning"
newdata_all$notes[newdata_all$Title=="DA: Junction City standoff being investigated as hate crime - WAOW - Newsline 9, Wausau News, Weather, Sports"]<-"duplicate"
newdata_all$notes[newdata_all$Title=="Man Charged In Hate Crime After Beating 2 Transgender Women In New York McDonald's"]<-"Patrick O'Meara"
newdata_all$notes[newdata_all$Title=="NY Man Charged With Hate Crime Attack on Transgender Women"]<-"duplicate"
newdata_all$notes[newdata_all$Title=="Hate crime on Ocean Park Blvd."]<-"Henry Lee"
newdata_all$notes[newdata_all$Title=="Arrest made in 'You live in Trump country now' gay-bashing attack"]<-"Brandon Ray Davis"

newdata_all<-subset(newdata_all, notes!="duplicate")

```


Combine Tate and Sara (2000-2300):

```{r}
mydata<-merge(sara, tate, by="Incident.number", all.x=TRUE)

#Clean up city names:
mydata$Incident.City.x<-as.character(mydata$Incident.City.x)
mydata$Incident.City.y<-as.character(mydata$Incident.City.y)

#Trailing spaces:
mydata$Incident.City.x<-trimws(mydata$Incident.City.x, which = c("both"))
mydata$Incident.City.y<-trimws(mydata$Incident.City.y, which = c("both"))

mydata$Year.of.Incident.x<-as.numeric(as.character(mydata$Year.of.Incident.x))
mydata$Year.of.Incident.y<-as.numeric(as.character(mydata$Year.of.Incident.y))
mydata$Day.of.Incident.x<-as.numeric(as.character(mydata$Day.of.Incident.x))
mydata$Day.of.Incident.y<-as.numeric(as.character(mydata$Day.of.Incident.y))
mydata$Month.of.Incident.x<-as.numeric(as.character(mydata$Month.of.Incident.x))
mydata$Month.of.Incident.y<-as.numeric(as.character(mydata$Month.of.Incident.y))
mydata$Notes.x<-as.character(mydata$Notes.x)
mydata$Notes.y<-as.character(mydata$Notes.y)
mydata$Title<-mydata$Title.x
mydata$URL<-mydata$URL.x

#Fix some cases:
mydata$Day.of.Incident.x[mydata$Title=="Second noose found at a DC museum within a week"]<-mydata$Day.of.Incident.y[mydata$Title=="Second noose found at a DC museum within a week"]<-1
mydata$Month.of.Incident.x[mydata$Title=="Second noose found at a DC museum within a week"]<-mydata$Month.of.Incident.y[mydata$Title=="Second noose found at a DC museum within a week"]<-6
mydata$Inc.Intensity.x[mydata$Title=="Second noose found at a DC museum within a week"]<-mydata$Inc.Intensity.y[mydata$Title=="Second noose found at a DC museum within a week"]<-2

mydata$Inc.Intensity.x[mydata$Title=="Hate Crime at African American Museum in DC"]<-mydata$Inc.Intensity.y[mydata$Title=="Hate Crime at African American Museum in DC"]<-2

mydata$Day.of.Incident.x[mydata$Title=="Another Noose Found At Construction Site: Five Noose Incidents In DC Area In Two Months"]<-mydata$Day.of.Incident.y[mydata$Title=="Another Noose Found At Construction Site: Five Noose Incidents In DC Area In Two Months"]<-1
mydata$Notes.x[mydata$Title=="Another Noose Found At Construction Site: Five Noose Incidents In DC Area In Two Months"]<-"construction site"
mydata$Notes.x[mydata$Title=="One of two men in custody in connection to hate crime assault" & mydata$URL=="http://brooklyn.news12.com/story/35573892/one-of-two-men-in-custody-in-connection-to-hate-crime-assault"]<-"umbrella laceration"

mydata$Notes.x[mydata$Title=="Man Yells Anti-White, Anti-Women Comments Before Punching Lady: Police" & mydata$URL=="http://www.nbcnewyork.com/news/local/Man-Yells-Anti-White-Anti-Women-Comments-Before-Punching-Woman-Police-425887404.html"]<-"punching"

mydata$Notes.x[mydata$Title=="Woman attacked on Brooklyn subway in apparent bias incident
" & mydata$URL=="http://abc7ny.com/news/woman-attacked-on-subway-in-apparent-bias-incident/2062011/"]<-"subway attack"

mydata$Notes.x[mydata$Title=="Victim of heinous racial attack laid to rest" & mydata$URL=="http://amsterdamnews.com/news/2017/jun/01/victim-heinous-racial-attack-laid-rest/"]<-"duplicate"



#Reorder
mydata<-mydata[, order(names(mydata))]
mydata<-mydata[order(mydata$Incident.City.x),]

mydata$match_city<-as.numeric(mydata$Incident.City.x==mydata$Incident.City.y)
mydata$match_month<-as.numeric(mydata$Month.of.Incident.x==mydata$Month.of.Incident.y)

#Combine the data on which the coders agree:
agree<-subset(mydata, subset=(match_city==1 & match_month==1))

agree<-agree[, order(names(agree))]
agree<-agree[order(agree$Incident.City.x),]

agree<-subset(agree, subset=!is.na(Month.of.Incident.x))


#Remove old incidents:
agree<-subset(agree, subset=Year.of.Incident.x>2016)

newdata<-cbind.data.frame(Title=agree$Title,URL=agree$URL)
newdata$day<-agree$Day.of.Incident.y
newdata$month<-agree$Month.of.Incident.y
newdata$year<-agree$Year.of.Incident.y
newdata$type<-agree$Incident.Type.y
newdata$issue<-agree$Issue.Identity.y
newdata$city<-agree$Incident.City.y
newdata$state<-agree$Incident.State.y
newdata$numdeaths<-agree$Num.Deaths.y
newdata$numvic<-agree$Num.Victims.y
newdata$numperp<-agree$Num.Perp.y
newdata$intensity<-agree$Inc.Intensity.y
newdata$notes<-paste(agree$Notes.x,agree$Notes.y)
newdata$inc.id<-agree$Incident.number

newdata<-newdata[, order(names(newdata))]
newdata<-newdata[order(newdata$city),]
#write.csv(newdata, "test1.csv", row.names = FALSE)

#Combine the data on which the coders disagree:
disagree<-subset(mydata, subset=(match_city!=1 | match_month!=1 | is.na(match_month)))

#Cases where the coders agree that it was a hate incident but disagree on city or month:
disagree1<-subset(disagree, subset=(Year.of.Incident.x==2017 | Year.of.Incident.y==2017))

#If they agree on the city:
disagree1_city<-subset(disagree1, subset=(match_city==1))

newdata1<-cbind.data.frame(Title=disagree1_city$Title,URL=disagree1_city$URL)
newdata1$day<-disagree1_city$Day.of.Incident.x
newdata1$month<-disagree1_city$Month.of.Incident.x
newdata1$year<-disagree1_city$Year.of.Incident.x
newdata1$type<-disagree1_city$Incident.Type.y
newdata1$issue<-disagree1_city$Issue.Identity.y
newdata1$city<-disagree1_city$Incident.City.y
newdata1$state<-disagree1_city$Incident.State.y
newdata1$numdeaths<-disagree1_city$Num.Deaths.y
newdata1$numvic<-disagree1_city$Num.Victims.y
newdata1$numperp<-disagree1_city$Num.Perp.y
newdata1$intensity<-disagree1_city$Inc.Intensity.y
newdata1$notes<-paste(disagree1_city$Notes.x,disagree1_city$Notes.y)
newdata1$inc.id<-disagree1_city$Incident.number


#If they agree on month, but disagree on city:
disagree1_mo<-subset(disagree1, subset=(match_city==0 & match_month==1))

#Correct some cities:

newdata2<-cbind.data.frame(Title=disagree1_mo$Title,URL=disagree1_mo$URL)
newdata2$day<-disagree1_mo$Day.of.Incident.x
newdata2$month<-disagree1_mo$Month.of.Incident.x
newdata2$year<-disagree1_mo$Year.of.Incident.x
newdata2$type<-disagree1_mo$Incident.Type.y
newdata2$issue<-disagree1_mo$Issue.Identity.y
newdata2$city<-disagree1_mo$Incident.City.y
newdata2$state<-disagree1_mo$Incident.State.y
newdata2$numdeaths<-disagree1_mo$Num.Deaths.y
newdata2$numvic<-disagree1_mo$Num.Victims.y
newdata2$numperp<-disagree1_mo$Num.Perp.y
newdata2$intensity<-disagree1_mo$Inc.Intensity.y
newdata2$notes<-paste(disagree1_mo$Notes.x,disagree1_mo$Notes.y)
newdata2$inc.id<-disagree1_mo$Incident.number

#Data on which the coders disagree:
disagree1_any<-subset(disagree1, subset=(match_city==0 & match_month==0))


#write.csv(disagree1_any, "test1.csv", row.names = FALSE)

#Clean up:

disagree1_any<-subset(disagree1_any, subset=(match_city==0 & match_month==0))
newdata3<-cbind.data.frame(Title=disagree1_any$Title,URL=disagree1_any$URL)
newdata3$day<-disagree1_any$Day.of.Incident.x
newdata3$month<-disagree1_any$Month.of.Incident.x
newdata3$year<-disagree1_any$Year.of.Incident.x
newdata3$type<-disagree1_any$Incident.Type.y
newdata3$issue<-disagree1_any$Issue.Identity.y
newdata3$city<-disagree1_any$Incident.City.y
newdata3$state<-disagree1_any$Incident.State.y
newdata3$numdeaths<-disagree1_any$Num.Deaths.y
newdata3$numvic<-disagree1_any$Num.Victims.y
newdata3$numperp<-disagree1_any$Num.Perp.y
newdata3$intensity<-disagree1_any$Inc.Intensity.y
newdata3$notes<-paste(disagree1_any$Notes.x,disagree1_any$Notes.y)
newdata3$inc.id<-disagree1_any$Incident.number

#Additional Incidents Found by Re-Reading the Sources:
inc1<-cbind.data.frame(Title="Another Noose Found At Construction Site: Five Noose Incidents In DC Area In Two Months.1",
                       URL="http://www.inquisitr.com/4267279/another-noose-found-at-construction-site-5-noose-incidents-in-dc-area-in-two-months/",
                       day=28,
                       month=5,
                       year=2017,
                       city="DC",
                       state=" ",
                       type="Noose",
                       issue="race",
                       numdeaths=0,
                       numvic="more than 1",
                       numperp="unknown",
                       intensity= "2",
                       notes="noose at museum--Additional incident found in article",
                       inc.id=2245.1)

inc2<-cbind.data.frame(Title="Another Noose Found At Construction Site: Five Noose Incidents In DC Area In Two Months.2",
                       URL="http://www.inquisitr.com/4267279/another-noose-found-at-construction-site-5-noose-incidents-in-dc-area-in-two-months/",
                       day=26,
                       month=5,
                       year=2017,
                       city="DC",
                       state=" ",
                       type="Noose",
                       issue="race",
                       numdeaths=0,
                       numvic="more than 1",
                       numperp="unknown",
                       intensity= "2",
                       notes="second noose at museum--Additional incident found in article",
                       inc.id=2245.2)

inc3<-cbind.data.frame(Title="Another Noose Found At Construction Site: Five Noose Incidents In DC Area In Two Months.3",
                       URL="http://www.inquisitr.com/4267279/another-noose-found-at-construction-site-5-noose-incidents-in-dc-area-in-two-months/",
                       day=27,
                       month=4,
                       year=2017,
                       city="College Park",
                       state="Maryland",
                       type="Noose",
                       issue="race",
                       numdeaths=0,
                       numvic="more than 1",
                       numperp="unknown",
                       intensity= "2",
                       notes="noose at Phi Kappa Tau house--Additional incident found in article",
                       inc.id=2245.3)


newdata_all1<-rbind.data.frame(newdata,newdata1,newdata2, newdata3, inc1,inc2,inc3)

newdata_all1<-newdata_all1[, order(names(newdata_all1))]
newdata_all1<-newdata_all1[order(newdata_all1$city),]

#Clean up:
newdata_all1$notes[newdata_all1$Title=="Hate Crime at African American Museum in DC"]<-"diff noose"
newdata_all1$notes[newdata_all1$Title=="Hate Crime at African American Museum in DC"]<-"diff noose"

newdata_all1$notes[newdata_all1$URL=="http://brooklyn.news12.com/story/35573892/one-of-two-men-in-custody-in-connection-to-hate-crime-assault"]<-"umbrella laceration"

newdata_all1$notes[newdata_all1$Title=="Victim of heinous racial attack laid to rest" & newdata_all1$URL=="http://amsterdamnews.com/news/2017/jun/01/victim-heinous-racial-attack-laid-rest/"]<-"duplicate"

newdata_all1$notes[newdata_all1$Title=="Basketball star, Lebron James, target of possible hate crime"]<-"Lebron James"

newdata_all1$notes[newdata_all1$Title %in% c("Hate crime against LeBron shows racism very much alive in today's America","How LeBron James' hate crime investigation highlights broader concern","Lebron James is the target of a possible hate crime")]<-"duplicate"

newdata_all1$notes[newdata_all1$Title=="Homeless Man Busted for Threatening to 'Blow Up Church' and 'Kill Christians'"]<-"duplicate"

newdata_all1$notes[newdata_all1$Title=="Accused Portland killer shows no remorse in court"]<-"Jeremy Joseph Christian"

newdata_all1$notes[newdata_all1$Title %in% c("Girl tearfully thanks men who lost lives defending her","Good Morning, News: Hate Crime Suspect's Crazy Arraignment, and Hero's Mom Writes Letter to Trump","Here's The Heartbreaking Letter A Portland Victim's Mom Wrote To Trump","Muslims Raise Over Half A Million Dollars For Portland Victims","Portland attacker pledged to slay Trump, Clinton in name of Nordic god","Portland stabbing recalls 1988 murder of Ethiopian grad student","Portland stabbing suspect shouts 'you've got no safe place!' at court appearance","Portland stabbing suspect: 'You call it terrorism, I call it patriotism!'","Portland Stabbings Are Reminder of Oregon's Long History of White Supremacy","Portland victim's mother appeals to Trump to condemn acts of hate")]<-"duplicate"

newdata_all1$notes[newdata_all1$URL=="https://www.vibe.com/2017/06/portland-stabbing-survivor-white-savior/"]<-"duplicate"

newdata_all1$notes[newdata_all1$Title=="SLO Mayor targeted in hate crime vandalism"]<-" "

newdata_all1$notes<-trimws(newdata_all1$notes, which = c("both"))
newdata_all1<-subset(newdata_all1, subset=notes!="duplicate")

```
Combine Tate and Ike: 

```{r}
mydata<-merge(ike, tate[tate$Incident.number>3999 & tate$Incident.number<5762,], by=c("Incident.number"), all.x=TRUE)

#Clean up city names:
mydata$Incident.City.x<-as.character(mydata$Incident.City.x)
mydata$Incident.City.y<-as.character(mydata$Incident.City.y)

#Trailing spaces:
mydata$Incident.City.x<-trimws(mydata$Incident.City.x, which = c("both"))
mydata$Incident.City.y<-trimws(mydata$Incident.City.y, which = c("both"))
mydata$Incident.City.x<-gsub("(^[[:space:]]*)|([[:space:]]*$)", "", mydata$Incident.City.x)

mydata$Incident.City.x[mydata$Incident.City.x=="New York City"]<-"New York"
mydata$Incident.City.y[mydata$Incident.City.y=="New York City"]<-"New York"

mydata$Incident.City.x<-toTitleCase(tolower(mydata$Incident.City.x))

mydata$Year.of.Incident.x<-as.numeric(as.character(mydata$Year.of.Incident.x))+2000
mydata$Year.of.Incident.y<-as.numeric(as.character(mydata$Year.of.Incident.y))
mydata$Day.of.Incident.x<-as.numeric(as.character(mydata$Day.of.Incident.x))
mydata$Day.of.Incident.y<-as.numeric(as.character(mydata$Day.of.Incident.y))
mydata$Month.of.Incident.x<-as.numeric(as.character(mydata$Month.of.Incident.x))
mydata$Month.of.Incident.y<-as.numeric(as.character(mydata$Month.of.Incident.y))
mydata$Notes.x<-as.character(mydata$Notes.x)
mydata$Notes.y<-as.character(mydata$Notes.y)

mydata<-mydata[, order(names(mydata))]
mydata<-mydata[order(mydata$Incident.City.x),]

#Clean up some cases:
mydata$Day.of.Incident.x[mydata$Title.x=="Albany officials call graffiti outside condo a hate crime"]<-mydata$Day.of.Incident.y[mydata$Title.x=="Albany officials call graffiti outside condo a hate crime"]<-21

mydata$Day.of.Incident.x[mydata$Incident.number==4989 | mydata$Incident.number==4997]<-mydata$Day.of.Incident.y[mydata$Incident.number==4989 | mydata$Incident.number==4997]<-17 #Free Dylann Roof — I hate n**gers': Hate crime suspects tag U of Michigan with racist graffiti

mydata$Day.of.Incident.x[mydata$Incident.number %in% c("4637","4638","4791","4794","4795","4796","4799","4865")]<-mydata$Day.of.Incident.y[mydata$Incident.number %in% c("4745","4747","4791","4794","4795","4796","4799","4865")]<-12 #Police think 2 Louisiana slayings likely racially motivated

mydata$Day.of.Incident.x[mydata$Incident.number %in% c("4637","4638","4644")]<-mydata$Day.of.Incident.y[mydata$Incident.number %in% c("4637","4638","4644")]<-10 #Bellevue police investigating suspected hate crime in Bellevue

mydata$Day.of.Incident.x[mydata$Incident.number==5609]<-mydata$Day.of.Incident.y[mydata$Incident.number==5609]<-22 #“Small riot” breaks out after racial tensions in Buffalo, KC Star says

mydata$Day.of.Incident.x[mydata$Incident.number %in% c("4806","4807","4808","4812","4814","4827","4828","4831")]<-mydata$Day.of.Incident.y[mydata$Incident.number %in% c("4806","4807","4808","4812","4814","4827","4828","4831")]<-18 #Castro Valley school truck vandalized with racist graffiti

mydata$Notes.x[mydata$Incident.number==5195]<-mydata$Notes.y[mydata$Incident.number==5195]<-"Jacob Nicely and Steven Page" #2 men face hate crime, battery charges

mydata$Notes.x[mydata$Incident.number %in% c("4772","4919")]<-mydata$Notes.y[mydata$Incident.number %in% c("4772","4919")]<-"duplicate"

mydata$Day.of.Incident.x[mydata$Incident.number %in% c("5195","4772","4919")]<-mydata$Day.of.Incident.y[mydata$Incident.number %in% c("5195","4772","4919")]<-16

mydata$State.x[mydata$Incident.number %in% c("5195","4772","4919")]<-mydata$State.y[mydata$Incident.number %in% c("5195","4772","4919")]<-"Illinois"

mydata$Day.of.Incident.y[mydata$Incident.number %in% c("4895","4897","4906","4907","4908","4945")]<-21 #first of three incidents of CMPD investigating hate crime after Jewish family finds swastika on back window of home

mydata$Day.of.Incident.y[mydata$Incident.number ==4722]<-15

#VIDEO: East Bay Jewish community concerned over recent hate crimes, says they're connected to alt-right rally
#Will code this as the Piedmont one and add the other two mentioned in the article as additional incidents.
mydata$Day.of.Incident.x[mydata$Incident.number==4219]<-mydata$Day.of.Incident.y[mydata$Incident.number==4219]<-17
mydata$Incident.City.x[mydata$Incident.number==4219]<-mydata$Incident.City.y[mydata$Incident.number==4219]<-"Piedmont"
mydata$Incident.State.x[mydata$Incident.number==4219]<-mydata$Incident.State.y[mydata$Incident.number==4219]<-"California"

mydata$Notes.x[mydata$Incident.number==4457]<-"duplicate of 4219"

#Police Investigate Discovery of Noose Outside Alameda High School as Hate Crime
mydata$Day.of.Incident.x[mydata$Incident.number %in% c("4562","4566","4567","4580","4593","4817")]<-mydata$Day.of.Incident.y[mydata$Incident.number %in% c("4562","4566","4567","4580","4593","4817")]<-5
mydata$Month.of.Incident.x[mydata$Incident.number %in% c("4562","4566","4567","4580","4593","4817")]<-mydata$Month.of.Incident.y[mydata$Incident.number %in% c("4562","4566","4567","4580","4593","4817")]<-9
mydata$Incident.City.x[mydata$Incident.number %in% c("4562","4566","4567","4580","4593","4817")]<-mydata$Incident.City.y[mydata$Incident.number %in% c("4562","4566","4567","4580","4593","4817")]<-"Alameda"
mydata$Incident.State.x[mydata$Incident.number %in% c("4562","4566","4567","4580","4593","4817")]<-mydata$Incident.State.y[mydata$Incident.number %in% c("4562","4566","4567","4580","4593","4817")]<-"California"
mydata$Notes.x[mydata$Incident.number==4817]<-"duplicate of 4562"

#Volcano Vista High students responsible for racist image on social media
mydata$Day.of.Incident.x[mydata$Incident.number==4456]<-mydata$Day.of.Incident.y[mydata$Incident.number==4456]<-29
mydata$Month.of.Incident.x[mydata$Incident.number==4456]<-mydata$Month.of.Incident.y[mydata$Incident.number==4456]<-8
mydata$Incident.City.x[mydata$Incident.number==4456]<-mydata$Incident.City.y[mydata$Incident.number==4456]<-"Albuquerque"
mydata$Incident.State.x[mydata$Incident.number==4456]<-mydata$Incident.State.y[mydata$Incident.number==4456]<-"New Mexico"

#Noose incident at Amherst College not a hate crime, DA rules
mydata$Day.of.Incident.x[mydata$Incident.number %in% c("5117","5126")]<-mydata$Day.of.Incident.y[mydata$Incident.number %in% c("5117","5126")]<-4
mydata$Month.of.Incident.x[mydata$Incident.number %in% c("5117","5126")]<-mydata$Month.of.Incident.y[mydata$Incident.number %in% c("5117","5126")]<-9
mydata$Incident.City.x[mydata$Incident.number %in% c("5117","5126")]<-mydata$Incident.City.y[mydata$Incident.number %in% c("5117","5126")]<-"Amherst"
mydata$Incident.State.x[mydata$Incident.number %in% c("5117","5126")]<-mydata$Incident.State.y[mydata$Incident.number %in% c("5117","5126")]<-"Massachusetts"

#Blotter: Suspects in Aubrey home invasion plead guilty to federal hate crimes
mydata$Day.of.Incident.x[mydata$Incident.number %in% c("4210","4335","4405")]<-mydata$Day.of.Incident.y[mydata$Incident.number %in% c("4210","4335","4405")]<-4

mydata$Notes.x[mydata$Incident.number %in% c("4210","4335","4405")]<-"duplicate Anthony Shelton, Nigel Garrett, Chancler Encalade and Cameron Ajiduah"

mydata$Notes.x[mydata$Incident.number ==4746]<-"duplicate of Kenneth James Gleason"

#NYC: Teen Charged With Hate Crime For Beating A Stranger For Being White
mydata$Incident.City.x[mydata$Incident.number==5162]<-mydata$Incident.City.y[mydata$Incident.number==5162]<-"New York"

#Simotas Meets With Egyptian Food Vendor, Hate Crime Target
mydata$Incident.City.x[mydata$Incident.number==4182]<-mydata$Incident.City.y[mydata$Incident.number==4182]<-"New York"
mydata$Notes.x[mydata$Incident.number==4182]<-"eggs thrown at Muslim food-truck owner"

mydata$match_city<-as.numeric(mydata$Incident.City.x==mydata$Incident.City.y)
mydata$match_month<-as.numeric(mydata$Month.of.Incident.x==mydata$Month.of.Incident.y)

#Combine the data on which the coders agree:
agree<-subset(mydata, subset=(match_city==1 & match_month==1))

agree<-agree[, order(names(agree))]
agree<-agree[order(agree$Incident.City.x),]

agree<-subset(agree, subset=!is.na(Month.of.Incident.x))


#Remove old incidents:
agree<-subset(agree, subset=Year.of.Incident.x==2017)

newdata<-cbind.data.frame(Title=agree$Title.x,URL=agree$URL.x)
newdata$day<-agree$Day.of.Incident.x
newdata$month<-agree$Month.of.Incident.x
newdata$year<-agree$Year.of.Incident.x
newdata$type<-agree$Incident.Type.x
newdata$issue<-agree$Issue.Identity.x
newdata$city<-agree$Incident.City.y
newdata$state<-agree$Incident.State.y
newdata$numdeaths<-agree$Num.Deaths.x
newdata$numvic<-agree$Num.Victims.x
newdata$numperp<-agree$Num.Perp.x
newdata$intensity<-agree$Inc.Intensity.x
newdata$notes<-paste(agree$Notes.x,agree$Notes.y)
newdata$inc.id<-agree$Incident.number


newdata<-newdata[, order(names(newdata))]
newdata<-newdata[order(newdata$city),]

#Combine the data on which the coders disagree:
disagree<-subset(mydata, subset=(match_city!=1 | match_month!=1 | is.na(match_month)))
#Cases where the coders agree that it was a hate incident but disagree on city or month:
disagree1<-subset(disagree, subset=(Year.of.Incident.x %in% c("2017","2018") | Year.of.Incident.y%in% c("2017","2018")))

#If they agree on the city:
disagree1_city<-subset(disagree1, subset=(match_city==1))

newdata1<-cbind.data.frame(Title=disagree1_city$Title.x,URL=disagree1_city$URL.x)
newdata1$day<-disagree1_city$Day.of.Incident.x
newdata1$month<-disagree1_city$Month.of.Incident.x
newdata1$year<-disagree1_city$Year.of.Incident.x
newdata1$type<-disagree1_city$Incident.Type.x
newdata1$issue<-disagree1_city$Issue.Identity.x
newdata1$city<-disagree1_city$Incident.City.y
newdata1$state<-disagree1_city$Incident.State.y
newdata1$numdeaths<-disagree1_city$Num.Deaths.x
newdata1$numvic<-disagree1_city$Num.Victims.x
newdata1$numperp<-disagree1_city$Num.Perp.x
newdata1$intensity<-disagree1_city$Inc.Intensity.x
newdata1$notes<-paste(disagree1_city$Notes.x,disagree1_city$Notes.y)
newdata1$inc.id<-disagree1_city$Incident.number

#If they agree on month, but disagree on city:
disagree1_mo<-subset(disagree1, subset=(match_city==0 & match_month==1))

newdata2<-cbind.data.frame(Title=disagree1_mo$Title.x,URL=disagree1_mo$URL.x)
newdata2$day<-disagree1_mo$Day.of.Incident.x
newdata2$month<-disagree1_mo$Month.of.Incident.x
newdata2$year<-disagree1_mo$Year.of.Incident.x
newdata2$type<-disagree1_mo$Incident.Type.x
newdata2$issue<-disagree1_mo$Issue.Identity.x
newdata2$city<-disagree1_mo$Incident.City.y
newdata2$state<-disagree1_mo$Incident.State.y
newdata2$numdeaths<-disagree1_mo$Num.Deaths.x
newdata2$numvic<-disagree1_mo$Num.Victims.x
newdata2$numperp<-disagree1_mo$Num.Perp.x
newdata2$intensity<-disagree1_mo$Inc.Intensity.x
newdata2$notes<-paste(disagree1_mo$Notes.x,disagree1_mo$Notes.y)
newdata2$inc.id<-disagree1_mo$Incident.number

#Data on which the coders disagree:
disagree1_any<-subset(disagree1, subset=(match_city!=1 & match_month!=1 | is.na(match_city) | is.na(match_month)))

#Disagreements other than the additional incidents found by Ike:
disagree1_any1<-disagree1_any[disagree1_any$Incident.number%%1==0,]
disagree1_any1<-subset(disagree1_any1, subset=!(is.na(disagree1_any1$URL.x) & is.na(disagree1_any1$URL.y)))

newdata3<-cbind.data.frame(Title=disagree1_any1$Title.x,URL=disagree1_any1$URL.x)
newdata3$day<-disagree1_any1$Day.of.Incident.x
newdata3$month<-disagree1_any1$Month.of.Incident.x
newdata3$year<-disagree1_any1$Year.of.Incident.x
newdata3$type<-disagree1_any1$Incident.Type.x
newdata3$issue<-disagree1_any1$Issue.Identity.x
newdata3$city<-disagree1_any1$Incident.City.x
newdata3$state<-disagree1_any1$Incident.State.x
newdata3$numdeaths<-disagree1_any1$Num.Deaths.x
newdata3$numvic<-disagree1_any1$Num.Victims.x
newdata3$numperp<-disagree1_any1$Num.Perp.x
newdata3$intensity<-disagree1_any1$Inc.Intensity.x
newdata3$notes<-disagree1_any1$Notes.x
newdata3$inc.id<-disagree1_any1$Incident.number


#Get additional incidents found in stories by Ike:
disagree1_add<-disagree1_any[disagree1_any$Incident.number%%1!=0 | is.na(disagree1_any$Incident.number),]
newdata4<-cbind.data.frame(Title=disagree1_add$Title.x,URL=disagree1_add$URL.x)
newdata4$day<-disagree1_add$Day.of.Incident.x
newdata4$month<-disagree1_add$Month.of.Incident.x
newdata4$year<-disagree1_add$Year.of.Incident.x
newdata4$type<-disagree1_add$Incident.Type.x
newdata4$issue<-disagree1_add$Issue.Identity.x
newdata4$city<-disagree1_add$Incident.City.x
newdata4$state<-disagree1_add$Incident.State.x
newdata4$numdeaths<-disagree1_add$Num.Deaths.x
newdata4$numvic<-disagree1_add$Num.Victims.x
newdata4$numperp<-disagree1_add$Num.Perp.x
newdata4$intensity<-disagree1_add$Inc.Intensity.x
newdata4$notes<-disagree1_add$Notes.x
newdata4$inc.id<-disagree1_add$Incident.number




#Additional incidents found by rereading the stories:
inc1<-cbind.data.frame(inc.id=4745.2,
                       Title="Baton Rouge man arrested for 'brutal murders' of two black people, police say.1",
                       URL="https://www.washingtonpost.com/news/post-nation/wp/2017/09/19/baton-rouge-man-arrested-for-brutal-murders-of-two-black-people-police-say/",
                       day=11,
                       month=9,
                       year=2017,
                       city="Baton Rouge",
                       state="Louisiana",
                       type="shooting",
                       issue="race",
                       numdeaths=0,
                       numvic=2,
                       numperp=1,
                       intensity= 3,
                       notes="Kenneth James Gleason--Additional incident found in article")

inc2<-cbind.data.frame(inc.id=4219.1,
                       Title="VIDEO: East Bay Jewish community concerned over recent hate crimes, says they're connected to alt-right rally.1",
                       URL="http://kron4.com/2017/08/23/video-east-bay-jewish-community-concerned-over-recent-hate-crimes-says-upcoming-alt-right-rally-is-to-blame/",
                       day=16,
                       month=8,
                       year=2017,
                       city="Alameda",
                       state="California",
                       type="vandalism",
                       issue="religion",
                       numdeaths=0,
                       numvic=0,
                       numperp="na",
                       intensity= 2,
                       notes="Additional incident found in article")

inc3<-cbind.data.frame(inc.id=4219.2,
                       Title="VIDEO: East Bay Jewish community concerned over recent hate crimes, says they're connected to alt-right rally.1",
                       URL="http://kron4.com/2017/08/23/video-east-bay-jewish-community-concerned-over-recent-hate-crimes-says-upcoming-alt-right-rally-is-to-blame/",
                       day=20,
                       month=8,
                       year=2017,
                       city="Alameda",
                       state="California",
                       type="hate flyers",
                       issue="religion",
                       numdeaths=0,
                       numvic=0,
                       numperp="na",
                       intensity= 2,
                       notes="Additional incident found in article")

inc1$city<-as.character(inc1$city)
inc2$city<-as.character(inc2$city)
inc3$city<-as.character(inc3$city)
inc1$notes<-as.character(inc1$notes)
inc2$notes<-as.character(inc2$notes)
inc3$notes<-as.character(inc3$notes)
inc1$intensity<-as.factor(inc1$intensity)
inc2$intensity<-as.factor(inc2$intensity)
inc3$intensity<-as.factor(inc3$intensity)
inc1$numdeaths<-as.factor(inc1$numdeaths)
inc2$numdeaths<-as.factor(inc2$numdeaths)
inc3$numdeaths<-as.factor(inc3$numdeaths)
inc1$numvic<-as.factor(inc1$numvic)
inc2$numvic<-as.factor(inc2$numvic)
inc3$numvic<-as.factor(inc3$numvic)

newdata_all2<-rbind.data.frame(newdata,newdata1,newdata2, newdata3, newdata4,inc1,inc2,inc3)

newdata_all2<-newdata_all2[, order(names(newdata_all2))]
#newdata_all2<-newdata_all2[order(newdata_all2$city),]

#Clean up:
newdata_all2$notes[newdata_all2$inc.id %in% c("5035","4697")]<-""
newdata_all2$notes[newdata_all2$note=="duplucate"]<-"duplicate"
newdata_all2<-subset(newdata_all2, subset=as.numeric(is.na(stringr::str_extract(newdata_all2$notes, "duplicate")))==1)

```


Data coded only by Tate:
```{r}
tate1<-tate[(tate$Incident.number>2300 & tate$Incident.number<4000) | tate$Incident.number>5761,]
tate1<-tate1[tate1$Hate.Incident==1,]


newdata<-cbind.data.frame(Title=tate1$Title,URL=tate1$URL)
newdata$day<-as.numeric(as.character(tate1$Day.of.Incident))
newdata$month<-as.numeric(as.character(tate1$Month.of.Incident))
newdata$year<-as.numeric(as.character(tate1$Year.of.Incident))
newdata$type<-tate1$Incident.Type
newdata$issue<-tate1$Issue.Identity
newdata$city<-trimws(as.character(tate1$Incident.City), which="both")
newdata$state<-trimws(as.character(tate1$Incident.State), which="both")
newdata$numdeaths<-tate1$Num.Deaths
newdata$numvic<-tate1$Num.Victims
newdata$numperp<-tate1$Num.Perp
newdata$intensity<-tate1$Inc.Intensity
newdata$notes<-as.character(tate1$Notes)
newdata$inc.id<-tate1$Incident.number



newdata<-newdata[, order(names(newdata))]
newdata<-newdata[newdata$year>2016,]

#Clean up:
newdata$notes[newdata$inc.id==7681]<-"Michael Ron David Kadar"
newdata$day[newdata$inc.id==7681]<-4 #Florida: threat to Chabad South Orlando school


inc1<-cbind.data.frame(inc.id=7681.1,
                       Title="Man indicted for hate crime and threats to Jewish Community Center and cyberstalking.1",
                       URL="http://www.wrbl.com/news/crime-watch/man-indicted-for-hate-crime-and-threats-to-jewish-community-center-and-cyberstalking/999050135",
                       day=4,
                       month=1,
                       year=2017,
                       city="Orlando",
                       state="Florida",
                       type="threat",
                       issue="religion",
                       numdeaths=0,
                       numvic=0,
                       numperp=1,
                       intensity= 2,
                       notes="Add inc, Michael Ron David Kadar, Jewish Academy")

inc2<-cbind.data.frame(inc.id=7681.2,
                       Title="Man indicted for hate crime and threats to Jewish Community Center and cyberstalking.2",
                       URL="http://www.wrbl.com/news/crime-watch/man-indicted-for-hate-crime-and-threats-to-jewish-community-center-and-cyberstalking/999050135",
                       day=5,
                       month=1,
                       year=2017,
                       city="Orlando",
                       state="Florida",
                       type="threat",
                       issue="religion",
                       numdeaths=0,
                       numvic=0,
                       numperp=1,
                       intensity= 2,
                       notes="Add inc, Michael Ron David Kadar Chabad South again")

inc3<-cbind.data.frame(inc.id=7681.3,
                       Title="Man indicted for hate crime and threats to Jewish Community Center and cyberstalking.3",
                       URL="http://www.wrbl.com/news/crime-watch/man-indicted-for-hate-crime-and-threats-to-jewish-community-center-and-cyberstalking/999050135",
                       day=5,
                       month=1,
                       year=2017,
                       city="Tampa",
                       state="Florida",
                       type="threat",
                       issue="religion",
                       numdeaths=0,
                       numvic=0,
                       numperp=1,
                       intensity= 2,
                       notes="Add inc, Michael Ron David Kadar, Tampa JCC Preschool North")

inc4<-cbind.data.frame(inc.id=7681.4,
                       Title="Man indicted for hate crime and threats to Jewish Community Center and cyberstalking.4",
                       URL="http://www.wrbl.com/news/crime-watch/man-indicted-for-hate-crime-and-threats-to-jewish-community-center-and-cyberstalking/999050135",
                       day=5,
                       month=1,
                       year=2017,
                       city="Tampa",
                       state="Florida",
                       type="threat",
                       issue="religion",
                       numdeaths=0,
                       numvic=0,
                       numperp=1,
                       intensity= 2,
                       notes="Add inc, Michael Ron David Kadar, Tampa JCC Preschool South")

inc5<-cbind.data.frame(inc.id=7681.5,
                       Title="Man indicted for hate crime and threats to Jewish Community Center and cyberstalking.5",
                       URL="http://www.wrbl.com/news/crime-watch/man-indicted-for-hate-crime-and-threats-to-jewish-community-center-and-cyberstalking/999050135",
                       day=9,
                       month=1,
                       year=2017,
                       city="Tampa",
                       state="Florida",
                       type="threat",
                       issue="religion",
                       numdeaths=0,
                       numvic=0,
                       numperp=1,
                       intensity= 2,
                       notes="Add inc, Michael Ron David Kadar, Tampa JCC Preschool South")

inc6<-cbind.data.frame(inc.id=7681.6,
                       Title="Man indicted for hate crime and threats to Jewish Community Center and cyberstalking.6",
                       URL="http://www.wrbl.com/news/crime-watch/man-indicted-for-hate-crime-and-threats-to-jewish-community-center-and-cyberstalking/999050135",
                       day=9,
                       month=1,
                       year=2017,
                       city="Orlando",
                       state="Florida",
                       type="threat",
                       issue="religion",
                       numdeaths=0,
                       numvic=0,
                       numperp=1,
                       intensity= 2,
                       notes="Add inc, Michael Ron David Kadar, Roth JCC")

inc7<-cbind.data.frame(inc.id=7681.7,
                       Title="Man indicted for hate crime and threats to Jewish Community Center and cyberstalking.7",
                       URL="http://www.wrbl.com/news/crime-watch/man-indicted-for-hate-crime-and-threats-to-jewish-community-center-and-cyberstalking/999050135",
                       day=9,
                       month=1,
                       year=2017,
                       city="Jacksonville",
                       state="Florida",
                       type="threat",
                       issue="religion",
                       numdeaths=0,
                       numvic=0,
                       numperp=1,
                       intensity= 2,
                       notes="Add inc, Michael Ron David Kadar, Jewish Comm Alliance")

inc8<-cbind.data.frame(inc.id=7681.8,
                       Title="Man indicted for hate crime and threats to Jewish Community Center and cyberstalking.8",
                       URL="http://www.wrbl.com/news/crime-watch/man-indicted-for-hate-crime-and-threats-to-jewish-community-center-and-cyberstalking/999050135",
                       day=18,
                       month=1,
                       year=2017,
                       city="Orlando",
                       state="Florida",
                       type="threat",
                       issue="religion",
                       numdeaths=0,
                       numvic=0,
                       numperp=1,
                       intensity= 2,
                       notes="Add inc, Michael Ron David Kadar, Roth JCC")

inc9<-cbind.data.frame(inc.id=7681.9,
                       Title="Man indicted for hate crime and threats to Jewish Community Center and cyberstalking.9",
                       URL="http://www.wrbl.com/news/crime-watch/man-indicted-for-hate-crime-and-threats-to-jewish-community-center-and-cyberstalking/999050135",
                       day=16,
                       month=2,
                       year=2017,
                       city="Orlando",
                       state="Florida",
                       type="threat",
                       issue="religion",
                       numdeaths=0,
                       numvic=0,
                       numperp=1,
                       intensity= 2,
                       notes="Add inc, Michael Ron David Kadar, Glenridge Middle School")

inc10<-cbind.data.frame(inc.id=7681.10,
                       Title="Man indicted for hate crime and threats to Jewish Community Center and cyberstalking.10",
                       URL="http://www.wrbl.com/news/crime-watch/man-indicted-for-hate-crime-and-threats-to-jewish-community-center-and-cyberstalking/999050135",
                       day=16,
                       month=2,
                       year=2017,
                       city="Orlando",
                       state="Florida",
                       type="threat",
                       issue="religion",
                       numdeaths=0,
                       numvic=0,
                       numperp=1,
                       intensity= 2,
                       notes="Add inc, Michael Ron David Kadar, airport")

inc11<-cbind.data.frame(inc.id=7681.11,
                       Title="Man indicted for hate crime and threats to Jewish Community Center and cyberstalking.11",
                       URL="http://www.wrbl.com/news/crime-watch/man-indicted-for-hate-crime-and-threats-to-jewish-community-center-and-cyberstalking/999050135",
                       day=20,
                       month=2,
                       year=2017,
                       city="Tampa",
                       state="Florida",
                       type="threat",
                       issue="religion",
                       numdeaths=0,
                       numvic=0,
                       numperp=1,
                       intensity= 2,
                       notes="Add inc, Michael Ron David Kadar, Tampa JCC Preschool")

inc12<-cbind.data.frame(inc.id=7681.12,
                       Title="Man indicted for hate crime and threats to Jewish Community Center and cyberstalking.12",
                       URL="http://www.wrbl.com/news/crime-watch/man-indicted-for-hate-crime-and-threats-to-jewish-community-center-and-cyberstalking/999050135",
                       day=9,
                       month=3,
                       year=2017,
                       city="Washington, D.C.",
                       state="NA",
                       type="threat",
                       issue="religion",
                       numdeaths=0,
                       numvic=0,
                       numperp=1,
                       intensity= 2,
                       notes="Add inc, Michael Ron David Kadar, Israeli Embassy")

inc13<-cbind.data.frame(inc.id=7681.13,
                       Title="Man indicted for hate crime and threats to Jewish Community Center and cyberstalking.13",
                       URL="http://www.wrbl.com/news/crime-watch/man-indicted-for-hate-crime-and-threats-to-jewish-community-center-and-cyberstalking/999050135",
                       day=7,
                       month=3,
                       year=2017,
                       city="Washington, D.C.",
                       state="NA",
                       type="threat",
                       issue="religion",
                       numdeaths=0,
                       numvic=0,
                       numperp=1,
                       intensity= 2,
                       notes="Add inc, Michael Ron David Kadar, Anti-Defamation League")

inc14<-cbind.data.frame(inc.id=7681.14,
                       Title="Man indicted for hate crime and threats to Jewish Community Center and cyberstalking.14",
                       URL="http://www.wrbl.com/news/crime-watch/man-indicted-for-hate-crime-and-threats-to-jewish-community-center-and-cyberstalking/999050135",
                       day=3,
                       month=1,
                       year=2017,
                       city="Athens",
                       state="Georgia",
                       type="threat",
                       issue="religion",
                       numdeaths=0,
                       numvic=0,
                       numperp=1,
                       intensity= 2,
                       notes="Add inc, Michael Ron David Kadar, U of G PD")


inc15<-cbind.data.frame(inc.id=7681.15,
                       Title="Man indicted for hate crime and threats to Jewish Community Center and cyberstalking.15",
                       URL="http://www.wrbl.com/news/crime-watch/man-indicted-for-hate-crime-and-threats-to-jewish-community-center-and-cyberstalking/999050135",
                       day=3,
                       month=1,
                       year=2017,
                       city="Athens",
                       state="Georgia",
                       type="threat",
                       issue="religion",
                       numdeaths=0,
                       numvic=0,
                       numperp=1,
                       intensity= 2,
                       notes="Add inc, Michael Ron David Kadar, AK")

newdata$notes[newdata$inc.id %in% c("2845","6327","6776","6553","2347","2341","5776","6226","5837","5765","5768")]<-""


newdata<-subset(newdata, subset=as.numeric(is.na(stringr::str_extract(newdata$notes, "duplicate")))==1)
newdata<-newdata[!is.na(newdata$city),]


newdata<-rbind.data.frame(newdata,inc1,inc2,inc3,inc4,inc5,inc6,inc7,inc8,inc9,inc10,inc11,inc12,inc13,inc14,inc15)


fulldata<-rbind.data.frame(newdata_all,newdata_all1, newdata_all2,newdata)
fulldata<-fulldata[fulldata$year>2016,]

#Clean up fulldata:

fulldata$notes[fulldata$inc.id %in% c("4150","4153","4154","4180","4189","4196","4771","4774","4785","4800")]<-"duplicate" #Anthony Shelton, Nigel Garrett, Chancler Encalade and Cameron Ajiduah
fulldata$notes[fulldata$inc.id==6]<-"Lauren Kirk-Coehlo"
fulldata$notes[fulldata$inc.id==4544]<-"duplicate" #Lauren Kirk-Coehlo

fulldata$notes[fulldata$inc.id==1176]<-"Jamie Hoffman"
fulldata$notes[fulldata$inc.id==5103.24]<-"racist graffiti"

fulldata$notes[fulldata$inc.id==515]<-"Marq Vincent Perez"

fulldata$notes[fulldata$inc.id==2845]<-"duplicate" #Marq Vincent Perez

fulldata$notes[fulldata$inc.id==5]<-"Dyrion Patterson and Jamyren Richard"

fulldata$notes[fulldata$inc.id==172]<-"Todd Williams"
fulldata$notes[fulldata$inc.id %in% c("4936","6327")]<-"duplicate Todd Williams"

fulldata<-subset(fulldata, subset=as.numeric(is.na(stringr::str_extract(fulldata$notes, "duplicate")))==1)

fulldata$notes[fulldata$inc.id==2]<-"" #Residents of NJ township receiving KKK promotional fliers

fulldata$notes[fulldata$inc.id==5528]<-"Mount Carmel Cemetery"
fulldata$notes[fulldata$inc.id==5540]<-"duplicate Mount Carmel Cemetery"

fulldata$notes[fulldata$inc.id==5485]<-"Gerald Sloane Wallace"
fulldata$notes[fulldata$inc.id %in% c("5462","5463","5464","5480")]<-"duplicate Gerald Sloane Wallace"

fulldata$notes[fulldata$inc.id==82]<-"Adam Purinton"
fulldata$notes[fulldata$inc.id==5642]<-"duplicate Adam Purinton"

fulldata$notes[fulldata$inc.id==4134]<-"Daniel Volkers"
fulldata$notes[fulldata$inc.id==4286]<-"duplicate Daniel Volkers"

fulldata$notes[fulldata$inc.id==4715]<-"Loudal Baez"

fulldata$notes[fulldata$inc.id==367]<-"Pasquale Vargas"

fulldata$city[fulldata$city=="D.C." | fulldata$city=="D.C" | fulldata$city=="DC" | fulldata$city=="Washington D.c."]<-"Washington, D.C."
fulldata$state[fulldata$city=="Washington, D.C."]<-"NA"

fulldata$notes[fulldata$inc.id==5138]<-"Joseph Woznik"
fulldata$notes[fulldata$inc.id %in% c("5158","5325","5456")]<-"duplicate Joseph Woznik"

fulldata$notes[fulldata$inc.id==664]<-"Joseph Giaquinto"
fulldata$notes[fulldata$inc.id==6776]<-"duplicate Joseph Giaquinto"

fulldata$notes[fulldata$inc.id==783]<-"Rudy Arana"
fulldata$notes[fulldata$inc.id==3427]<-"duplicate Rudy Arana"

fulldata$notes[fulldata$inc.id==842]<-"Joe Ottomanelli"
fulldata$notes[fulldata$inc.id==4818]<-"duplicate Joe Ottomanelli"

fulldata$notes[fulldata$inc.id==5427]<-"Damien Rodriguez"
fulldata$notes[fulldata$inc.id %in% c("5444","5488","5103.19","5494.1","7725","5454")]<-"duplicate Damien Rodriguez"

fulldata$notes[fulldata$inc.id==4307]<-"duplicate noose at Phi Kappa Tau"

fulldata$notes[fulldata$inc.id==1250]<-"Joseph Leineweber"
fulldata$notes[fulldata$inc.id==5103.17]<-"duplicate Joseph Leineweber"

fulldata$notes[fulldata$inc.id==5139]<-"Conner Prout and John Havermann"
fulldata$numperp[fulldata$inc.id==5139]<-2
fulldata$notes[fulldata$inc.id %in% c("5215","5216","5217","6553")]<-"duplicate Conner Prout and John Havermann"

fulldata$notes[fulldata$inc.id==2043]<-"Sean Urbanski"
fulldata$notes[fulldata$inc.id %in% c("4471","5385","5494","2347")]<-"duplicate Sean Urbanski"

fulldata$notes[fulldata$inc.id==5584]<-"Hadden Kennedy and Jodan Peck"
fulldata$city[fulldata$inc.id==5584]<-"Goshen"
fulldata$state[fulldata$inc.id==5584]<-"California"
fulldata$day[fulldata$inc.id==5584]<-22
fulldata$month[fulldata$inc.id==5584]<-10
fulldata$numperp[fulldata$inc.id==5584]<-2
fulldata$numvic[fulldata$inc.id==5584]<-1
fulldata$numdeaths[fulldata$inc.id==5584]<-0
fulldata$type[fulldata$inc.id==5584]<-"attempted murder"

fulldata$notes[fulldata$inc.id==4159]<-"duplicate of 4156"

fulldata$notes[fulldata$inc.id==3104]<-"Antoine Thomas"
fulldata$Title[fulldata$inc.id==4479.1]<-"Man's jaw broken in possible anti-gay hate crime in Brooklyn"
fulldata$URL[fulldata$inc.id==4479.1]<-"http://www.metroweekly.com/2017/08/mans-jaw-broken-anti-gay-hate-crime-brooklyn/"
fulldata$notes[fulldata$inc.id==4479.1]<-"duplicate Antoine Thomas"

fulldata$numperp[fulldata$inc.id==2190]<-1
fulldata$notes[fulldata$inc.id==2190]<-"a different train incident from Antoine Thomas"

fulldata$notes[fulldata$inc.id %in% c("5622","5103.14")]<-"duplicate Jeremy Joseph Christian"

fulldata$notes[fulldata$inc.id==5103.13]<-"duplicate of 2216"

fulldata$notes[fulldata$inc.id==5256]<-"Tyler Austin"
fulldata$notes[fulldata$inc.id==2304]<-"duplicate Tyler Austin"

fulldata$notes[fulldata$inc.id==4599]<-"William “Billy” Boucher"

fulldata$notes[fulldata$inc.id==5612]<-"duplicate of 5592"

fulldata$notes[fulldata$inc.id==2574]<-"Sjarpe"

fulldata$notes[fulldata$inc.id==5103.09]<-"middle-schooler harassed"

fulldata$notes[fulldata$inc.id==2736]<-"Andre Marcel Siftsoff"
fulldata$notes[fulldata$inc.id==2772]<-"duplicate Andre Marcel Siftsoff"

fulldata$notes[fulldata$inc.id==5253]<-"Darwin Martinez Torres"
fulldata$notes[fulldata$inc.id %in% c("5248","5266","5354")]<-"duplicate Darwin Martinez Torres"

fulldata$notes[fulldata$inc.id %in% c("3270","3364")]<-"duplicate of 5035"

fulldata$notes[fulldata$inc.id %in% c("5213","3798")]<-"duplicate of 5717"

fulldata$notes[fulldata$inc.id==5433]<-"Vincent Randazzese"
fulldata$city[fulldata$inc.id==5433]<-"Pittsford"
fulldata$notes[fulldata$inc.id==5193]<-"duplicate Vincent Randazzese"

fulldata$notes[fulldata$inc.id==5226]<-"nazi flyers"
fulldata$city[fulldata$inc.id==5226]<-"East Greenville"
fulldata$state[fulldata$inc.id==5226]<-"Pennsylvania"
fulldata$day[fulldata$inc.id==5226]<-10
fulldata$month[fulldata$inc.id==5226]<-10
fulldata$intensity[fulldata$inc.id==5226]<-2
fulldata$numdeaths[fulldata$inc.id==5226]<-0
fulldata$numperp[fulldata$inc.id==5226]<-"at least 1"
fulldata$numvic[fulldata$inc.id==5226]<-"na"
fulldata$notes[fulldata$inc.id==5238]<-"duplicate of 5226"


fulldata$notes[fulldata$inc.id==4458]<-"Arnold Moody"
fulldata$notes[fulldata$inc.id %in% c("4459","4466","7589","7777")]<-"duplicates of Arnold Moody"

fulldata$notes[fulldata$inc.id==4516]<-"Agustin Garcia"
fulldata$notes[fulldata$inc.id==4512]<-"duplicate Agustin Garcia"

URL<-"https://www.readingeagle.com/ap/article/fear-resolve-and-more-security-at-charlottesvilles-temple"
fulldata$URL <- factor(fulldata$URL, levels = c(levels(fulldata$URL), URL)) #added a new level to this factor
fulldata$URL[fulldata$inc.id==4020]<-URL

fulldata$URL <- factor(fulldata$URL, levels = c(levels(fulldata$URL), "https://chicago.eater.com/2017/6/7/15754568/anti-muslim-incident-teen-girls-video-chicago-suburb-hickory-hills-pepes-mexican-restaurant")) #added a new level to this factor
fulldata$URL[fulldata$inc.id==2314]<-"https://chicago.eater.com/2017/6/7/15754568/anti-muslim-incident-teen-girls-video-chicago-suburb-hickory-hills-pepes-mexican-restaurant"


fulldata$notes[fulldata$inc.id==4386]<-"Daniel Borden"

fulldata$notes[fulldata$inc.id==3682]<-"James Fields"

fulldata$numvic <- factor(fulldata$numvic, levels = c(levels(fulldata$numvic),"41")) #added a new level to this factor
fulldata$numvic[fulldata$inc.id==3682]<-"41"
fulldata$notes[fulldata$inc.id==4039]<-"duplicate James Fields"

fulldata$notes[fulldata$inc.id==5664]<-"Edward Evseev, Mark Barrancos,and Bruno Camacho"
fulldata$notes[fulldata$inc.id %in% c("5647","5648","5649","5656","5670","5672","4492")]<-"duplicate Edward Evseev, Mark Barrancos,and Bruno Camacho"

fulldata$notes[fulldata$inc.id %in% c("3998","4139")]<-"duplicates of 4219.1 and 4219.2"

fulldata$notes[fulldata$inc.id ==4287]<-"international attack"

fulldata$notes[fulldata$inc.id ==4406]<-"Gregory Brzoza"
fulldata$notes[fulldata$inc.id %in% c("4417","4418","4126","4243")]<-"duplicate Gregory Brzoza"
fulldata$city[fulldata$inc.id ==4406]<-"Cleveland"

fulldata$notes[fulldata$inc.id ==4177]<-"a man punched an old lady"

fulldata$notes[fulldata$inc.id ==4186]<-"George Rissell"
fulldata$notes[fulldata$inc.id ==4233]<-"duplicate George Rissell"

fulldata$notes[fulldata$inc.id ==4151]<-"Alberto Campos"
fulldata$notes[fulldata$inc.id ==4161]<-"duplicate Alberto Campos"

fulldata$notes[fulldata$inc.id ==4370]<-"duplicate of 4372 and 4372.1"

fulldata$notes[fulldata$inc.id ==4368]<-"Zachary Stanton"
fulldata$notes[fulldata$inc.id ==5021]<-"duplicate Zachary Stanton"

fulldata$notes[fulldata$inc.id ==4378]<-"Marion Forrest, Frankie Brouwer"
fulldata$notes[fulldata$inc.id ==4431]<-"duplicate Marion Forrest, Frankie Brouwer"

fulldata$notes[fulldata$inc.id %in% c("4377","4427","4479")]<-"duplicate of 4443"

fulldata$notes[fulldata$inc.id ==5679]<- "Brianna Rae Brochu"
fulldata$notes[fulldata$inc.id %in% c("5675","5751")]<- "duplicate Brianna Rae Brochu"

fulldata$notes[fulldata$inc.id ==5040]<-"Michael Todd Birkl"
fulldata$notes[fulldata$inc.id %in% c("5044","5046","5067","4421")]<-"duplicate Michael Todd Birkl"

fulldata$notes[fulldata$inc.id ==4456]<-"duplicate of 4470"

fulldata$notes[fulldata$inc.id ==4546]<-"Artyom Manukyan"
fulldata$notes[fulldata$inc.id %in% c("4529","4535","4773")]<-"duplicate Artyom Manukyan"

fulldata$notes[fulldata$inc.id ==4955]<-"Andrew Vrba, Isis Schauer, Briana Calderas"
fulldata$notes[fulldata$inc.id %in% c("4925","4927","4928","4930","4932","4934","4935","4937","4939","4940","4942","4943","4946","4948","4949","4950","4951","4953","4954","4984","4985","5045","5155")]<-"duplicate Andrew Vrba, Isis Schauer, Briana Calderas"

fulldata$notes[fulldata$inc.id ==5117]<-"noose at Amherst College’s Pratt Field"
fulldata$notes[fulldata$inc.id ==5126]<-"duplicate noose at Amherst College’s Pratt Field"

fulldata$notes[fulldata$inc.id ==4776]<-"duplicate of 4560"

fulldata$notes[fulldata$inc.id ==4826]<-"duplicate of 4724"

fulldata$notes[fulldata$inc.id ==5199]<-"Rocky Lee Nibert and Delia Dawn Carr"
fulldata$city[fulldata$inc.id ==5199]<-"Point Pleasant"
fulldata$state[fulldata$inc.id ==5199]<-"West Virginia"
fulldata$day[fulldata$inc.id ==5199]<-6
fulldata$month[fulldata$inc.id ==5199]<-10
fulldata$numvic[fulldata$inc.id ==5199]<-1

fulldata$notes[fulldata$inc.id ==5201]<-"Jason Edward Cooper and Donald Lucas Prichard"
fulldata$day[fulldata$inc.id ==5201]<-8
fulldata$month[fulldata$inc.id ==5201]<-10
fulldata$city[fulldata$inc.id ==5201]<-"Spokane"
fulldata$state[fulldata$inc.id ==5201]<-"Washington"

fulldata$notes[fulldata$inc.id ==5154]<-"Andrew Alan Carruthers"
fulldata$notes[fulldata$inc.id %in% c("4834","5156","4801")]<-"duplicate Andrew Alan Carruthers"

fulldata$notes[fulldata$inc.id ==5043]<-"duplicate of 5042"

fulldata$notes[fulldata$inc.id ==4871]<-"Rachel Tuszynski"
fulldata$notes[fulldata$inc.id ==5544]<-"duplicate Rachel Tuszynski"

fulldata$notes[fulldata$inc.id %in% c("5059","5081")]<-"duplicate of 5038"

fulldata$notes[fulldata$inc.id==5065]<-"Jeffery Masters"
fulldata$notes[fulldata$inc.id %in% c("5070","5092","5700")]<-"duplicate of Jeffery Masters"

fulldata$notes[fulldata$inc.id ==5479]<-"duplicate of 5457"

fulldata$notes[fulldata$inc.id ==5198]<-"duplicate of 5201"

fulldata$notes[fulldata$inc.id %in% c("5191","5666")]<-"duplicate of 5176"

fulldata$notes[fulldata$inc.id ==5630]<-"duplicate of 6226"

fulldata$notes[fulldata$inc.id ==5837]<-"duplicate of 5734"

fulldata$notes[fulldata$inc.id ==5628]<- "Fortress of Hope Church"
fulldata$notes[fulldata$inc.id %in% c("5636","5662")]<-"duplicate of Fortress of Hope Church"

fulldata$notes[fulldata$inc.id ==5768]<- "duplicate of 5696"

fulldata$city[fulldata$inc.id ==8052]<-"Sierra Blanca"
fulldata$state[fulldata$inc.id ==8052]<-"Texas"
fulldata$notes[fulldata$inc.id ==8052]<-"abuse of detainees"

fulldata$day[fulldata$inc.id ==7992]<-10
fulldata$notes[fulldata$inc.id ==7984]<-"duplicate of 7992 Virgin Mary statue"

fulldata$notes[fulldata$inc.id ==8165]<-"duplicate of 8150"

fulldata$notes[fulldata$inc.id ==5221]<-"David Harris, Jesse Harris and Austin Taggart"
fulldata$notes[fulldata$inc.id %in% c("5222","5235")]<-"duplicate David Harris, Jesse Harris and Austin Taggart"
fulldata$day[fulldata$inc.id ==5221]<-18
fulldata$month[fulldata$inc.id ==5221]<-4

fulldata$notes[fulldata$inc.id ==2229]<-"Yaacov Shemesh"
fulldata$day[fulldata$inc.id ==2229]<-"from Dec 2016 to May 2017"

fulldata$month[fulldata$inc.id ==2272]<-6
fulldata$day[fulldata$inc.id ==2272]<-3

fulldata$day[fulldata$inc.id ==1494]<-12

fulldata$day[fulldata$inc.id ==4873]<-13

fulldata$notes[fulldata$inc.id ==2056]<-"duplicate LeBron James"

fulldata$day[fulldata$inc.id ==4463]<-16

fulldata$city[fulldata$inc.id ==4379]<-"Brooklyn"
fulldata$intensity[fulldata$inc.id ==4379]<-3
fulldata$numvic[fulldata$inc.id ==4379]<-3
fulldata$day[fulldata$inc.id ==4379]<-26
fulldata$month[fulldata$inc.id ==4379]<-8
fulldata$notes[fulldata$inc.id ==4380]<-"duplicate of 4379"

fulldata$notes[fulldata$inc.id %in% c("4298","4344")]<-"duplicate of 7532"

fulldata$notes[fulldata$inc.id ==2202]<-"duplicate of 2341"

fulldata$state[fulldata$inc.id ==5054]<-"Wyoming"


fulldata$day[fulldata$inc.id ==5270]<-28
fulldata$month[fulldata$inc.id ==5270]<-9

fulldata$notes[fulldata$inc.id ==5355]<-"duplicate of 5270"

fulldata$day[fulldata$inc.id ==5095]<-25

fulldata$notes[fulldata$inc.id ==4964]<-"duplicate of 4957"
fulldata$URL <- factor(fulldata$URL, levels = c(levels(fulldata$URL),"https://www.nbcnews.com/news/us-news/american-university-finds-confederate-flag-signs-posted-after-antiracist-presentation-n805266")) #added a new level to this factor
fulldata$URL[fulldata$inc.id ==4957]<-"https://www.nbcnews.com/news/us-news/american-university-finds-confederate-flag-signs-posted-after-antiracist-presentation-n805266"
fulldata$day[fulldata$inc.id ==4957]<-26
fulldata$month[fulldata$inc.id ==4957]<-9

fulldata$URL <- factor(fulldata$URL, levels = c(levels(fulldata$URL),"https://www.apnews.com/79d21c88b9fa4ee2a10496d45c1792fd")) #added a new level to this factor
fulldata$URL[fulldata$inc.id ==115]<-"https://www.apnews.com/79d21c88b9fa4ee2a10496d45c1792fd"



fulldata$Title <- factor(fulldata$Title, levels = c(levels(fulldata$Title),"American University Finds Confederate Flag Signs Posted After Anti-Racist Presentation"))
fulldata$Title[fulldata$inc.id ==4957]<-"American University Finds Confederate Flag Signs Posted After Anti-Racist Presentation"

fulldata$notes[fulldata$inc.id==5466]<-"duplicate of Gerald Sloane Wallace"

fulldata$notes[fulldata$inc.id==4602]<-"duplicate of 82"
fulldata$numvic[fulldata$inc.id==83]<-3

fulldata$notes[fulldata$inc.id==5402]<-"Bennett Smith"
fulldata$notes[fulldata$inc.id==5357]<-"duplicate Bennett Smith"

fulldata$notes[fulldata$inc.id==6264]<-"Michael E. Dickey"
fulldata$notes[fulldata$inc.id==6259]<-"duplicate Michael E. Dickey"

fulldata$notes[fulldata$inc.id==6825]<-"Jermaine Hines Jr."


fulldata$state[fulldata$inc.id==6729]<-"Massachusetts"

fulldata$notes[fulldata$inc.id==6533]<-"Jeremy Dean Thacker"

fulldata$notes[fulldata$inc.id==6518]<-"Matthew R. Ellis"
fulldata$notes[fulldata$inc.id==5103.16]<-"Noah Kronsteiner"

fulldata$state[fulldata$inc.id==7654]<-"New York"
fulldata$city[fulldata$inc.id==7654]<-"New York" #Queens

fulldata$state[fulldata$inc.id==3232]<-"North Carolina"

fulldata$notes[fulldata$inc.id==3125]<-"James Patrick Billiot and Justin William Rifanburg "
fulldata$state[fulldata$inc.id==3125]<-"North Dakota"

#Typoes
fulldata$state<-gsub("(^[[:space:]]*)|([[:space:]]*$)", "", fulldata$state)
fulldata$city[fulldata$inc.id==6177]<-"Cinnaminson" 
fulldata$city[fulldata$inc.id==6353]<-"Huntley" 
fulldata$city[fulldata$inc.id==3955]<-"Jackson"
fulldata$city[fulldata$inc.id==7357]<-"Jonesborough" 
fulldata$city[fulldata$inc.id==5895]<-"Washington, D.C."
fulldata$city[fulldata$inc.id==3317]<-"Kalkaska"
fulldata$city[fulldata$inc.id==3257]<-"Dallas"


fulldata$state[fulldata$state=="South Carlolina"]<-"South Carolina"
fulldata$state[fulldata$state=="Conneticut"]<-"Connecticut"
fulldata$state[fulldata$state=="Virgina"]<-"Virginia"
fulldata$state[fulldata$state=="WestVirginia"]<-"West Virginia"
fulldata$state[fulldata$state=="Lousiana"]<-"Louisiana"
fulldata$city[fulldata$city=="Berkley" | fulldata$city=="Berkely"]<-"Berkeley"
fulldata$state[fulldata$state=="Califronia"]<-"California"
fulldata$city[fulldata$city=="Clarement"]<-"Claremont"
fulldata$city[fulldata$city=="Mt. Hood"]<-"Mount Hood"
fulldata$city[fulldata$city=="Orangeville"]<-"Orangevale"
fulldata$city[fulldata$city=="La Cañada Valley"]<-"La Canada Flintridge"
fulldata$city[fulldata$city=="Cook County"]<-"McCook"
fulldata$city[fulldata$city=="Gavelston"]<-"Galveston"
fulldata$city[fulldata$inc.id==5926]<-"Hoboken" 
fulldata$city[fulldata$city =="New york" |fulldata$city == "Astoria"| fulldata$city =="Manhatten"| fulldata$city =="Manhattan" | fulldata$city=="Brooklyn"| fulldata$city =="Chelsea" | fulldata$city =="Chealsea" | fulldata$city =="Long Island" | fulldata$city =="Staten Island" | fulldata$city =="SoHo" | fulldata$city =="West Queens"]<-"New York"
fulldata$state[fulldata$city=="New York"]<-"New York"
fulldata$city[fulldata$city=="Lincold Square"]<-"Chicago"
fulldata$city[fulldata$city=="Logan Heights"]<-"San Diego"
fulldata$city[fulldata$city=="Hillcrest"]<-"San Diego"
fulldata$city[fulldata$city=="Malibu West"]<-"Malibu"
fulldata$city[fulldata$city=="Pacific Palisades"]<-"Los Angeles"
fulldata$city[fulldata$city=="Philadeplphia" | fulldata$city=="Philedelphia"]<-"Philadelphia"
fulldata$city[fulldata$city=="Pittsburg"]<-"Pittsburgh"
fulldata$city[fulldata$city=="Scottesdale"]<-"Scottsdale"
fulldata$city[fulldata$city=="Southhampton"]<-"Southampton"
fulldata$city[fulldata$city=="St Charles"]<-"Saint Charles"
fulldata$city[fulldata$city=="St Louis" | fulldata$city=="St. Louis" ]<-"Saint Louis"
fulldata$city[fulldata$city=="St. Cloud"]<-"Saint Cloud"
fulldata$city[fulldata$city=="St. Joseph"]<-"Saint Joseph"
fulldata$city[fulldata$city=="Tuskaloosa"]<-"Tuscaloosa"
fulldata$city[fulldata$city=="West Coniva"]<-"West Covina"
fulldata$city[fulldata$city=="Woodbrige"]<-"Woodbridge"
fulldata$city[fulldata$city=="Woodland Hills"]<-"Los Angeles"
fulldata$city[fulldata$city=="Ysleta del Sur Pueblo"]<-"El Paso"


fulldata$city[fulldata$inc.id==6775]<-"Margate City"
fulldata$city[fulldata$inc.id==4057]<-"Roseville"
fulldata$city[fulldata$inc.id==5443]<-"New York"
fulldata$city[fulldata$inc.id==1443]<-"Nassau"
fulldata$city[fulldata$inc.id==3010]<-"Silver Spring"
fulldata$city[fulldata$inc.id==5103.16]<-"Tigard"

fulldata$year[fulldata$inc.id==7144]<-2017
fulldata$day[fulldata$inc.id==7144]<-13

fulldata$year[fulldata$inc.id==8114]<-2017
fulldata$year[fulldata$inc.id==6942]<-2017
fulldata$year[fulldata$inc.id==8147]<-2017
fulldata$year[fulldata$inc.id==3218]<-2017

inc1<-cbind.data.frame(inc.id=5644.1,
                       Title="Jewelry store targeted in recent hate crimes.1",
                       URL="http://nypost.com/2017/10/30/jewelry-store-targeted-in-recent-hate-crimes/",
                       day=6,
                       month=11,
                       year=2017,
                       city="New York",
                       state="New York",
                       type="threat",
                       issue="religion",
                       numdeaths=0,
                       numvic=0,
                       numperp="at least 1",
                       intensity= 1,
                       notes="Add inc, Jewelry store")

inc2<-cbind.data.frame(inc.id=1494.1,
                       Title="UNH Police Seek Public Assistance In Solving Racial Crimes.1",
                       URL="http://wokq.com/unh-police-seek-public-assistance-in-solving-racial-crimes/",
                       day=13,
                       month=5,
                       year=2017,
                       city="Durham",
                       state="New Hampshire",
                       type="threat",
                       issue="race",
                       numdeaths=0,
                       numvic=1,
                       numperp="at least 1",
                       intensity= 3,
                       notes="Add inc, a rock thrown at a minority student")

inc3<-cbind.data.frame(inc.id=1494.2,
                       Title="UNH Police Seek Public Assistance In Solving Racial Crimes.2",
                       URL="http://wokq.com/unh-police-seek-public-assistance-in-solving-racial-crimes/",
                       day=14,
                       month=5,
                       year=2017,
                       city="Durham",
                       state="New Hampshire",
                       type="threat",
                       issue="race",
                       numdeaths=0,
                       numvic=1,
                       numperp="at least 1",
                       intensity= 1,
                       notes="Add inc, hate language")

fulldata<-rbind.data.frame(fulldata,inc1, inc2, inc3)

fulldata<-subset(fulldata, subset=as.numeric(is.na(stringr::str_extract(fulldata$notes, "duplicate")))==1)
fulldata<-subset(fulldata, subset=as.numeric(is.na(stringr::str_extract(fulldata$notes, "duplucate")))==1)
fulldata<-subset(fulldata, subset=as.numeric(is.na(stringr::str_extract(fulldata$notes, "international attack")))==1)
Date<-paste(as.character(fulldata$day),as.character(fulldata$month),as.character(fulldata$year),sep="/")
fulldata$date<-as.Date(Date, "%d/%m/%Y")

fulldata<-unique(fulldata)
fulldata<-fulldata[order(fulldata$date,fulldata$city),]
fulldata<-fulldata[!is.na(fulldata$date),]
fulldata<-fulldata[!is.na(fulldata$inc.id),]
write.csv(fulldata, "CleanData/hatedata.csv", row.names = FALSE)

```

